import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CategoryCard } from '../components/CategoryCard'
import { HelpCTA } from '../components/HelpCTA'
import { SearchBar } from '../components/SearchBar'
import { TutorialCard } from '../components/TutorialCard'
import { categories, priorityTopics } from '../data/categories'
import { tutorials } from '../data/tutorials'

export function Home() {
  return <><section className="border-b border-line bg-[#eef5f6]"><div className="mx-auto max-w-6xl px-5 py-18 text-center lg:px-8 lg:py-24"><p className="mb-5 text-sm font-bold uppercase tracking-[0.16em] text-[#507283]">Central de Ajuda Digital</p><h1 className="text-4xl font-bold tracking-tight text-ink sm:text-5xl">Olá, como podemos ajudar?</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-muted-ink">Encontre tutoriais simples para resolver suas principais dúvidas digitais.</p><div className="mx-auto mt-8 max-w-3xl"><SearchBar /></div><p className="mt-4 text-sm text-muted-ink">ou escolha uma categoria para encontrar rapidamente a ajuda que você precisa</p></div></section><main className="mx-auto max-w-6xl px-5 lg:px-8"><section className="py-16"><SectionTitle title="Encontre ajuda por categoria" description="Escolha uma ferramenta ou uma habilidade para começar." /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => <CategoryCard key={category.id} category={category} />)}</div></section><section className="border-t border-line py-16"><SectionTitle title="O que mais precisa de ajuda?" description="Os assuntos em destaque foram priorizados a partir das necessidades mais frequentes identificadas na pesquisa." /><div className="mt-8 grid gap-px overflow-hidden rounded-xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">{priorityTopics.map((topic) => <Link key={topic.title} to={`/categorias/${topic.category}`} className="group bg-white p-5 transition-colors hover:bg-[#f7faf9]"><h3 className="flex items-center justify-between font-bold text-ink">{topic.title}<ArrowRight className="h-4 w-4 text-muted-ink group-hover:text-ink" /></h3><p className="mt-2 text-sm leading-5 text-muted-ink">{topic.description}</p></Link>)}</div></section><section className="border-t border-line py-16"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><SectionTitle title="Tutoriais mais procurados" description="Passo a passo claro para você aprender e resolver." /><Link to="/tutoriais" className="text-sm font-bold text-[#315d70] hover:text-ink">Ver todos os tutoriais</Link></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{tutorials.slice(0, 6).map((tutorial) => <TutorialCard key={tutorial.id} tutorial={tutorial} />)}</div></section><HelpCTA /></main></>
}

function SectionTitle({ title, description }) { return <div><h2 className="text-2xl font-bold tracking-tight text-ink sm:text-3xl">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-ink">{description}</p></div> }
